// шардирование по media_type
// репликация каждого шарда master - slave один к одному

Table media {
  id uuid [primary key]
  type media_type
  format nvarchar
  content byte[]
}

enum media_type {
  photo
  audio
  video
}

// Ref: mongo.dbml:profile.photos <> media.id // many-to-many