// шардирование по user_id
// асинхронная репликация каждого шарда один к одному вида master-slave

Table profile {
  id bigint [primary key]
  user_id uuid
  name varchar
  surname varchar
  description text
  address varchar
  photos uuid[]
  interests varchar
  created_at timestamp
  modified_at timestamp
}

// Ref: profile.photos <> ceph.dbml:media.id // many-to-many
// Note: user_id get from Authentification-Authorization external service