// шардирование не используется, т.к. потеряются преимущества графовой БД
// синхронная репликация один к одному вида master-slave

Table relationships {
  source_user_id uuid
  target_user_id uuid
  type relationships_type
  created_at timestamp
}

// Ref: user_id < relationships.source_user_id // one-to-many
// Ref: user_id < relationships.target_user_id // one-to-many
// Note: enum relationships_type { follow, friend, relative, couple }
// Note: user_id get from Authentification-Authorization external service