@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(geoDns, "Geo DNS", "Cloudflare", "GeoDNS + CDN")
Container(loadBalancer, "Load Balancer + API Gateway", "Nginx", "Uses round robin")

System_Boundary(mediaSystem, "Media system") {
    Container(mediaService, "Media Service", "Управление медиа-контентом пользователей", $tags="webApp")
    ContainerDb(mediaDatabase, "Media database", "S3 облачная БД", "Хранение медиа-контента пользователей",  $tags="db")
}

Rel(user, geoDns, "")
Rel(geoDns, loadBalancer, "")
Rel(loadBalancer, mediaSystem, "Фото, видео, звук")
Rel(mediaService, mediaDatabase, "")
@enduml