@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(geoDns, "Geo DNS", "Cloudflare", "GeoDNS + CDN")
Container(loadBalancer, "Load Balancer + API Gateway", "Nginx", "Uses round robin")

System_Boundary(analyticsSystem, "Analytics system") {
    Container(activityService, "Activity Service", "Управление статистикой постов и пользователей", $tags="webApp")
    ContainerDb(activityDatabase, "Activity database", "Mongo шардинг по идентификатору поста", "Хранение аналитики постов и пользователей",  $tags="db")
}

Rel(user, geoDns, "")
Rel(geoDns, loadBalancer, "")
Rel(loadBalancer, analyticsSystem, "Лайки, дизлайки, статистика просмотров")
Rel(activityService, activityDatabase, "")
@enduml