@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(geoDns, "Geo DNS", "Cloudflare", "GeoDNS + CDN")
Container(loadBalancer, "Load Balancer + API Gateway", "Nginx", "Uses round robin")
ContainerQueue(messageQueue, "Events queue", "Kafka", "Очередь сообщений для событий")

Container(relationsSystem, "Relations system", "Software system", "Создание и хранение графа зависимостей друзей и подписчиков")
Container(coreSystem, "Core system", "Software system", "Создание и хранение постов и комментариев")
Container(messagesSystem, "Messages system", "Software system", "Создание и хранение сообщений и чатов")
System_Boundary(analyticsSystem, "Analytics system") {
    Container(activityService, "Activity Service", "Управление статистикой постов и пользователей", $tags="webApp")
    ContainerDb(activityDatabase, "Activity database", "Mongo шардинг по идентификатору поста", "Хранение аналитики постов и пользователей",  $tags="db")
}
Container(mediaSystem, "Media system", "Software system", "Хранение медиа-контента")

Rel(user, geoDns, "")
Rel(geoDns, loadBalancer, "")
Rel(loadBalancer, relationsSystem, "Добавление и удаление друзей и подписчиков")
Rel(loadBalancer, coreSystem, "Создание постов и комментариев")
Rel(loadBalancer, analyticsSystem, "Лайки, дизлайки, статистика просмотров")
Rel(loadBalancer, messagesSystem, "Сообщения и чаты")
Rel(loadBalancer, mediaSystem, "Фото, видео, звук")
Rel(relationsSystem, messageQueue, "")
Rel(coreSystem, messageQueue, "")
Rel(messagesSystem, messageQueue, "")
Rel(activityService, activityDatabase, "")
@enduml